###
PUT http://localhost:3003/api/blogs/65437e1d37008ceb8e96b013
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5pb3NuaSIsImlkIjoiNjU0MDBhMGYwY2E1MzUyZTU5OTRjZmE2IiwiaWF0IjoxNjk4OTUzNDk4LCJleHAiOjE2OTg5NTcwOTh9.XfvdIqzulh6T4ksfX3t4u3PD7mGDX5KdYE0oL9yn8ls

{
  "title": "Newer title",
  "likes": 3
}