POST http://localhost:3003/api/users
Content-Type: application/json

{
      "username": "test",
      "name": "Test user",
      "password": "test"
}
###
POST http://localhost:3001/api/users
Content-Type: application/json

{
      "username": "niosni",
      "name": "Niklas Niemelä",
      "password": "salasana"
}
###
POST http://localhost:3001/api/users
Content-Type: application/json

{
      "name": "Niklas Niemelä",
      "password": "salasana"
}
###
POST http://localhost:3001/api/users
Content-Type: application/json

{
      "username": "niosni",
      "name": "Niklas Niemelä"
}